# Generated by Django 4.1.2 on 2022-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='was born'),
        ),
        migrations.AlterField(
            model_name='director',
            name='place_of_birth',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='place_of_death',
            field=models.CharField(max_length=120),
        ),
    ]
