# Generated by Django 4.1.2 on 2022-10-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_director_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='place_of_birth',
            field=models.CharField(max_length=120, verbose_name='Place of birth'),
        ),
        migrations.AlterField(
            model_name='director',
            name='place_of_death',
            field=models.CharField(max_length=120, verbose_name='Place of death'),
        ),
    ]
