# Generated by Django 4.1.2 on 2022-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_cinema_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='event_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
