# Generated by Django 4.1.2 on 2022-10-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_cinema_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.venue'),
        ),
    ]
