# Generated by Django 4.1.2 on 2022-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_cinema_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
