# Generated by Django 4.1.2 on 2022-10-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='event_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
