# Generated by Django 4.1.2 on 2022-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_cinema_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
