# Generated by Django 4.1.2 on 2022-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
