# Generated by Django 4.1.2 on 2022-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_cinema_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
